name: monitor
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
  - cron: '0 8 * * 1'

jobs:
  psychopy:
    timeout-minutes: 5
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      LATEST_RELEASE: 2023.2.3
    steps:
      - name: Retrieve PsychoPy latest release
        id: psychopy_latest
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: psychopy/psychopy
          excludes: prerelease, draft
      - name: Compare release versions
        run: |
          if [ "$LATEST_RELEASE" != "${{ steps.psychopy_latest.outputs.release }}" ]; then
            exit 1
          fi
      - name: Create GitHub issue
        if: failure()
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ github.token }}
          title: PsychoPy released a new version!
          body: |
            Please visit https://github.com/psychopy/psychopy/releases and review the changes.
            [Failed Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
          assignees: mscheltienne
