name: test
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
  - cron: '0 8 * * 1'

jobs:
  test:
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [3.8, 3.9, "3.10"]
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
      - name: Update pip and setuptools
        run: python -m pip install --progress-bar off --upgrade pip setuptools wheel
      - name: Install psychopy
        uses: ./
      - name: Check install
        run: |
          python -m pip show psychopy psychtoolbox
          python -c "import psychopy"
